# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # MCP客户端指标
  - job_name: 'mcp-client'
    static_configs:
      - targets: ['mcp-client:8001']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Prometheus自身指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Redis指标（如果启用了redis_exporter）
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

# 告警规则（可选）
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093